import Header from '../components/Header/Header.js'
import PageTitle from '../components/Layout/PageTitle'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <PageTitle title='Home'>
        <title>Seja Bem Vindo - </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </PageTitle>
      Hi
    </div>
  )
}
